- name: This playbook  will install, configure and deploy a custom web page into nginx web server
  hosts: all
  vars:
    - greeting_msg: DevOps!
    - provisioner_tool: Docker
    - conf_mgr_tool: Ansible
  tasks:
    - name: Install nginx web server into Ubuntu box
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      apt: name=nginx state=latest update_cache=yes

    - name: Fix meta https issue by replacing with http url into CentOS box
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

    - name: Install Extra Packages for Enterprise Linux(EPEL) into CentOS box
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=epel-release state=latest 

    - name: Install nginx web server into CentOS box
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=nginx state=latest 
  
    - name: Create custom web root folder
      file: path=/var/html state=directory mode=0777

    - name: Configure nginx to support custom web root folder in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      copy: src=default dest=/etc/nginx/sites-available/default

    - name: Configure nginx to support custom web root folder in CentOS 
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf

    - name: Restart nginx web server
      #service: name=nginx state=restarted enabled=true
      shell: service nginx restart

    - name: Retrieve IP address of ansible nodes
      command: hostname -i
      register: ip_address

    - debug: var=ip_address

    - name: Deploy a custom web page into remote nginx web server
      template: src=index.html.j2 dest=/var/html/index.html
